sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Vafh34xb6yiapJnKKyQIwdcSey7VtkM+KSLeMn43OszX62K6B3MglB9LxiN/py8sPoFuthMV4nnScJ/UfvoHZj5C9Qu61CWjj4e+0s6H8iqvtnnsPgZcC/NqiS7hrAu1lfA6lGBR1C+141f0npyuQpDw1inc/JTrCOYOs/zIm1liHiMj1S+yrBP0trDYqwvQkiS7d5y/qUoQbggnzigyivcIS+vwwIsWIW2dnorjcaPWUK41+wcVT22cOTdxUhdXwCI2cyCSoTqQjypl7svn8EITyGpw0PV0U0OuKPTMt1IdMtTlncS0oIF6amnm5igm6ifA4CwvKhkFb9rQDrbedRdaNrW+1FIOo0roeYwF2suAX0i03Mb/4X7Yj3GSfogJE0qj485sLBVdKJaLb9PGHacjFS35Ew4ZEs34nWDRLOoA+6e19u3rZtukmG2d1cNSK9SAIrJdmAee5iehYpLPURZQ0SL1soqAUHTvRQxr0jFtOnS7/Ex89Gauk1nT13W3+G6N0NT1ZWWC3UICokzdpLOSJo8ooZpYK9zhgVqPGoDxg1R1IKL51U4A897YSVNRn+sYv+s+vNC50rBc96kFMPbJec9xxvvmP4kqnPycBq0ivKfUiEtXteSbYMOgZ7QI+4iAF4rUIlmGMnNhmLdAbI5meVtvL9Z3U4FcSOQuhDQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Lectures-on-Evolution--13-Essay--3-from--Science-and-Hebrew-Tradition-_2629
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy